### ISSUE TITLE
UnsupportedClassVersionError: jetbrains/buildServer/serverSide/ConfigActionFactory : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcDebRepository#6]
When compiling on Java7.
Java8 in Java7 mode (-source, -target) works fine.

Look at building from TC 9.1 libs if possible.

**Comment by netwolfuk** [comment]
```
[10:19:47][Step 1/1] -------------------------------------------------------
[10:19:47][Step 1/1]  T E S T S
[10:19:47][Step 1/1] -------------------------------------------------------
[10:19:48][Step 1/1] org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
[10:19:48][Step 1/1] java.lang.reflect.InvocationTargetException
[10:19:48][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:19:48][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[10:19:48][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:19:48][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:606)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
[10:19:48][Step 1/1] Caused by: java.lang.UnsupportedClassVersionError: jetbrains/buildServer/serverSide/ConfigActionFactory : Unsupported major.minor version 52.0
[10:19:48][Step 1/1] 	at java.lang.ClassLoader.defineClass1(Native Method)
[10:19:48][Step 1/1] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
[10:19:48][Step 1/1] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[10:19:48][Step 1/1] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[10:19:48][Step 1/1] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[10:19:48][Step 1/1] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[10:19:48][Step 1/1] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[10:19:48][Step 1/1] 	at java.security.AccessController.doPrivileged(Native Method)
[10:19:48][Step 1/1] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[10:19:48][Step 1/1] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[10:19:48][Step 1/1] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[10:19:48][Step 1/1] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[10:19:48][Step 1/1] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[10:19:48][Step 1/1] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
[10:19:48][Step 1/1] 	at java.lang.Class.getMethod0(Class.java:2866)
[10:19:48][Step 1/1] 	at java.lang.Class.getMethod(Class.java:1676)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.util.ReflectionUtils.tryGetMethod(ReflectionUtils.java:57)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isSuiteOnly(JUnit3TestChecker.java:64)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isValidJUnit3Test(JUnit3TestChecker.java:59)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.accept(JUnit3TestChecker.java:54)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:51)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:97)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
[10:19:48][Step 1/1] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
[10:19:48][Step 1/1] 	... 9 more
[10:19:48][Step 1/1] 
```
